### ISSUE TITLE
NAN invalid value

### ISSUE THREAD

**Issue by ysqi** [evabase/evabase#73]
测试发现在提取全部Gas Fund 时，点击 [Max] 带入到输入框的 Value 是  `NaN`。
 
![action](https://user-images.githubusercontent.com/2821085/177952466-281ae633-adad-480c-9ad4-f0fcd1ea2c3f.gif)

**Comment by cl510804194** [comment]
done

**Comment by ysqi** [comment]
> done

@cl510804194 请给出测试该问题的网址。

**Comment by ysqi** [comment]
https://deploy-preview-42--beamish-raindrop-evabase.netlify.app/   Test Pass
